// versao-react/src/components/ProjetoAtual.jsx
function contar(total, singular, plural) {
  return `${total} ${total === 1 ? singular : plural}`;
}

function ProjetoAtual({ projeto, tarefas, projetos }) {
  let nome = "Todas as tarefas";
  let resumo = `${contar(tarefas.length, "tarefa", "tarefas")} em ${contar(
    projetos.length,
    "projeto",
    "projetos"
  )}`;

  if (projeto) {
    const totalProjeto = tarefas.filter(
      (tarefa) => tarefa.projetoId === projeto.id
    ).length;

    nome = projeto.nome;
    resumo = [projeto.cliente, contar(totalProjeto, "tarefa", "tarefas")]
      .filter(Boolean)
      .join(" · ");
  }

  return (
    <div className="projeto-atual">

      <div>
        <h2 id="projeto-atual-nome">{nome}</h2>
        <p className="projeto-cliente" id="projeto-atual-cliente">
          {resumo}
        </p>
      </div>

      <button
        type="button"
        id="btn-editar-projeto"
        className="btn"
        hidden={!projeto}
      >
        Editar projeto
      </button>

    </div>
  );
}

export default ProjetoAtual;

// versao-angular/src/app/components/projeto-atual/projeto-atual.ts
import { Component, computed, input, output } from '@angular/core';
import { Projeto } from '../../models/projeto';
import { Tarefa } from '../../models/tarefa';

function contar(total: number, singular: string, plural: string): string {
  return `${total} ${total === 1 ? singular : plural}`;
}

@Component({
  imports: [],
  selector: 'app-projeto-atual',
  styleUrl: './projeto-atual.css',
  templateUrl: './projeto-atual.html',
})
export class ProjetoAtual {
  projeto = input<Projeto>();
  tarefas = input.required<Tarefa[]>();
  projetos = input.required<Projeto[]>();

  readonly editar = output<void>();

  protected readonly nome = computed(() => this.projeto()?.nome ?? 'Todas as tarefas');

  protected readonly resumo = computed(() => {
    const projeto = this.projeto();

    if (!projeto) {
      return `${contar(this.tarefas().length, 'tarefa', 'tarefas')} em ${contar(
        this.projetos().length,
        'projeto',
        'projetos',
      )}`;
    }

    const totalProjeto = this.tarefas().filter(
      (tarefa) => tarefa.projetoId === projeto.id,
    ).length;

    return [projeto.cliente, contar(totalProjeto, 'tarefa', 'tarefas')]
      .filter(Boolean)
      .join(' · ');
  });
}
