// versao-react/src/components/FormularioTarefa.jsx
import { useEffect, useRef, useState } from "react";
import { ESTADOS, PRIORIDADES } from "../data/opcoes";

// Serve para criar (tarefa = null) e para editar. O App muda a "key" sempre
// que o formulário abre, por isso cada abertura começa com um estado novo.
function FormularioTarefa({
  aberto,
  tarefa,
  projetos,
  projetoInicialId,
  onGuardar,
  onFechar,
}) {
  const dialogRef = useRef(null);
  const tituloRef = useRef(null);

  const [titulo, setTitulo] = useState(tarefa?.titulo ?? "");
  const [descricao, setDescricao] = useState(tarefa?.descricao ?? "");
  const [projetoId, setProjetoId] = useState(tarefa?.projetoId ?? projetoInicialId);
  const [prioridade, setPrioridade] = useState(tarefa?.prioridade ?? "media");
  const [estado, setEstado] = useState(tarefa?.estado ?? "por-fazer");
  const [erro, setErro] = useState(false);

  // showModal() é um método do elemento DOM, por isso é preciso o ref.
  useEffect(() => {
    if (aberto && !dialogRef.current.open) {
      dialogRef.current.showModal();
    }
  }, [aberto]);

  function submeter(evento) {
    evento.preventDefault();

    const tituloLimpo = titulo.trim();

    if (!tituloLimpo) {
      setErro(true);
      tituloRef.current.focus();
      return;
    }

    onGuardar({
      titulo: tituloLimpo,
      descricao: descricao.trim(),
      prioridade,
      estado,
      projetoId,
    });
  }

  return (
    <dialog
      ref={dialogRef}
      id="modal-tarefa"
      className="modal"
      aria-labelledby="modal-titulo"
      onClose={onFechar}
    >

      <form
        id="form-tarefa"
        className="form"
        method="dialog"
        noValidate
        onSubmit={submeter}
      >

        <h2 id="modal-titulo">{tarefa ? "Editar tarefa" : "Nova tarefa"}</h2>

        <input type="hidden" id="tarefa-id" defaultValue={tarefa?.id ?? ""} />

        <label htmlFor="tarefa-titulo-input">
          Título <span aria-hidden="true">*</span>
        </label>

        <input
          ref={tituloRef}
          type="text"
          id="tarefa-titulo-input"
          className="campo"
          required
          maxLength={80}
          value={titulo}
          aria-invalid={erro ? "true" : undefined}
          onChange={(evento) => {
            setTitulo(evento.target.value);
            setErro(false);
          }}
        />

        <p className="erro" id="erro-titulo" hidden={!erro}>
          O título é obrigatório.
        </p>

        <label htmlFor="tarefa-descricao-input">Descrição</label>

        <textarea
          id="tarefa-descricao-input"
          className="campo"
          rows={4}
          maxLength={500}
          value={descricao}
          onChange={(evento) => setDescricao(evento.target.value)}
        ></textarea>

        <label htmlFor="tarefa-projeto-input">Projeto</label>

        <select
          id="tarefa-projeto-input"
          className="campo"
          value={projetoId}
          onChange={(evento) => setProjetoId(evento.target.value)}
        >
          {projetos.map((projeto) => (
            <option key={projeto.id} value={projeto.id}>
              {projeto.nome}
            </option>
          ))}
        </select>

        <div className="form-linha">

          <div>

            <label htmlFor="tarefa-prioridade-input">Prioridade</label>

            <select
              id="tarefa-prioridade-input"
              className="campo"
              value={prioridade}
              onChange={(evento) => setPrioridade(evento.target.value)}
            >
              {Object.entries(PRIORIDADES).map(([valor, rotulo]) => (
                <option key={valor} value={valor}>
                  {rotulo}
                </option>
              ))}
            </select>

          </div>

          <div>

            <label htmlFor="tarefa-estado-input">Estado</label>

            <select
              id="tarefa-estado-input"
              className="campo"
              value={estado}
              onChange={(evento) => setEstado(evento.target.value)}
            >
              {ESTADOS.map((opcao) => (
                <option key={opcao.valor} value={opcao.valor}>
                  {opcao.rotulo}
                </option>
              ))}
            </select>

          </div>

        </div>

        <div className="form-acoes">

          <button
            type="button"
            id="btn-cancelar"
            className="btn"
            onClick={onFechar}
          >
            Cancelar
          </button>
          <button type="submit" className="btn btn-primario">
            Guardar
          </button>

        </div>

      </form>

    </dialog>
  );
}

export default FormularioTarefa;

// versao-angular/src/app/components/formulario-tarefa/formulario-tarefa.ts
import { Component, ElementRef, inject, input, signal, viewChild } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ESTADOS, PRIORIDADES } from '../../data/opcoes';
import { Projeto } from '../../models/projeto';
import { Estado, Prioridade, Tarefa } from '../../models/tarefa';
import { TarefaService } from '../../services/tarefa-service';
import { obrigatorio } from '../../utils/validadores';

@Component({
  imports: [ReactiveFormsModule],
  selector: 'app-formulario-tarefa',
  styleUrl: './formulario-tarefa.css',
  templateUrl: './formulario-tarefa.html',
})
export class FormularioTarefa {
  projetos = input.required<Projeto[]>();

  private readonly tarefaService = inject(TarefaService);

  // showModal() e focus() são métodos do elemento DOM, por isso é preciso
  // chegar aos elementos com viewChild.
  private readonly dialogo = viewChild.required<ElementRef<HTMLDialogElement>>('dialogo');
  private readonly campoTitulo = viewChild.required<ElementRef<HTMLInputElement>>('campoTitulo');

  protected readonly estados = ESTADOS;
  protected readonly prioridades = PRIORIDADES;
  protected readonly ordem: Prioridade[] = ['baixa', 'media', 'alta'];

  // nonNullable: ao fazer reset, cada campo volta a um texto e não a null.
  protected readonly form = new FormGroup({
    titulo: new FormControl('', {
      nonNullable: true,
      validators: [obrigatorio, Validators.maxLength(80)],
    }),
    descricao: new FormControl('', {
      nonNullable: true,
      validators: Validators.maxLength(500),
    }),
    projetoId: new FormControl('', { nonNullable: true }),
    prioridade: new FormControl<Prioridade>('media', { nonNullable: true }),
    estado: new FormControl<Estado>('por-fazer', { nonNullable: true }),
  });

  // null ao criar; a tarefa que se está a editar ao editar.
  protected readonly emEdicao = signal<Tarefa | null>(null);

  // O erro só aparece depois de tentar guardar, e some ao escrever.
  protected readonly erro = signal(false);

  // Chamado pelo Painel. Cada abertura começa com o formulário limpo, ou com
  // os dados da tarefa a editar.
  abrir(projetoId: string, tarefa: Tarefa | null = null): void {
    this.emEdicao.set(tarefa);
    this.form.reset({
      titulo: tarefa?.titulo ?? '',
      descricao: tarefa?.descricao ?? '',
      projetoId,
      prioridade: tarefa?.prioridade ?? 'media',
      estado: tarefa?.estado ?? 'por-fazer',
    });
    this.erro.set(false);
    this.dialogo().nativeElement.showModal();
  }

  protected guardar(evento: Event): void {
    // Com method="dialog" o browser fechava o dialog mesmo com erros.
    evento.preventDefault();

    if (this.form.invalid) {
      this.erro.set(true);
      this.campoTitulo().nativeElement.focus();
      return;
    }

    const { titulo, descricao, projetoId, prioridade, estado } = this.form.getRawValue();
    const dados = {
      titulo: titulo.trim(),
      descricao: descricao.trim(),
      prioridade,
      estado,
      projetoId,
    };
    const tarefa = this.emEdicao();

    if (tarefa) {
      this.tarefaService.atualizar(tarefa.id, dados);
    } else {
      this.tarefaService.adicionar(dados);
    }

    this.fechar();
  }

  protected fechar(): void {
    this.dialogo().nativeElement.close();
  }
}
