// versao-react/src/components/Quadro.jsx
import { ESTADOS } from "../data/opcoes";
import ListaTarefas from "./ListaTarefas";

function Quadro({ tarefas, projetos }) {
  return (
    <main className="quadro" id="quadro">

      {ESTADOS.map((estado) => (
        <ListaTarefas
          key={estado.valor}
          estado={estado.valor}
          titulo={estado.titulo}
          tarefas={tarefas.filter((tarefa) => tarefa.estado === estado.valor)}
          projetos={projetos}
        />
      ))}

    </main>
  );
}

export default Quadro;

// versao-angular/src/app/components/quadro/quadro.ts
import { Component, input } from '@angular/core';
import { ESTADOS } from '../../data/opcoes';
import { Projeto } from '../../models/projeto';
import { Estado, Tarefa } from '../../models/tarefa';
import { ListaTarefas } from '../lista-tarefas/lista-tarefas';

@Component({
  imports: [ListaTarefas],
  selector: 'app-quadro',
  styleUrl: './quadro.css',
  templateUrl: './quadro.html',
})
export class Quadro {
  tarefas = input.required<Tarefa[]>();
  projetos = input.required<Projeto[]>();

  protected readonly estados = ESTADOS;

  protected tarefasDe(estado: Estado): Tarefa[] {
    return this.tarefas().filter((tarefa) => tarefa.estado === estado);
  }
}
