// versao-angular/src/app/components/lista-tarefas/lista-tarefas.ts
import { Component, input } from '@angular/core';
import { Projeto } from '../../models/projeto';
import { Estado, Tarefa } from '../../models/tarefa';
import { CartaoTarefa } from '../cartao-tarefa/cartao-tarefa';

@Component({
  imports: [CartaoTarefa],
  selector: 'app-lista-tarefas',
  styleUrl: './lista-tarefas.css',
  templateUrl: './lista-tarefas.html',
})
export class ListaTarefas {
  estado = input.required<Estado>();
  titulo = input.required<string>();
  tarefas = input.required<Tarefa[]>();
  projetos = input.required<Projeto[]>();

  protected projetoDe(id: string): Projeto | undefined {
    return this.projetos().find((projeto) => projeto.id === id);
  }
}

// versao-react/src/components/ListaTarefas.jsx
import Tarefa from "./Tarefa";

function ListaTarefas({ estado, titulo, tarefas, projetos }) {
  return (
    <section className="coluna" data-estado={estado}>

      <header className="coluna-topo">
        <h2>{titulo}</h2>
        <span className="contador">{tarefas.length}</span>
      </header>

      <div className="coluna-lista">

        {tarefas.map((tarefa) => (
          <Tarefa
            key={tarefa.id}
            tarefa={tarefa}
            projeto={projetos.find((projeto) => projeto.id === tarefa.projetoId)}
          />
        ))}

      </div>

    </section>
  );
}

export default ListaTarefas;
